encoding: utf-8
lang: ja
timezone: Asia/Tokyo

plugins: ["jekyll-remote-theme", "jekyll-feed", "jekyll-sitemap"]
remote_theme: ress997/jekyll-lime

url: http://example.com
title: Example Domain
description: Example Site
copyright: 2022 example.com
